In [2]:
import numpy as np


In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
a1=np.array(range(1,11))
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a1=np.arange(1,11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a = np.arange(16)

In [9]:
a=a.reshape((4,4))

In [10]:
a.ndim

2

In [11]:
a=a.reshape((2,2,4))

In [12]:
a.ndim

3

In [30]:
a1 = np.array([2,1,5,4,3,5,6,7,3,10,2,3]).reshape(3,4)
a1

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [31]:
a1.ravel() # converts into one dimensional array


array([ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3])

In [43]:
a2=a1.reshape(1,3,4)
a2

array([[[ 2,  1,  5,  4],
        [ 3,  5,  6,  7],
        [ 3, 10,  2,  3]]])

In [44]:
a2.shape()

TypeError: 'tuple' object is not callable

In [45]:
a2=a2.squeeze()
a2

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [46]:
a2.shape()

TypeError: 'tuple' object is not callable

In [48]:
a1 = np.arange(0,5)
a2 = a1.T

In [49]:
print(a1)
print(a2)

[0 1 2 3 4]
[0 1 2 3 4]


In [53]:
a1= np.array([4,3,7,9,2,3,9,6,1,4,7,6,11,4,8,7]).reshape((4,4))
a1

array([[ 4,  3,  7,  9],
       [ 2,  3,  9,  6],
       [ 1,  4,  7,  6],
       [11,  4,  8,  7]])

In [54]:
a2=a1.T
a2

array([[ 4,  2,  1, 11],
       [ 3,  3,  4,  4],
       [ 7,  9,  7,  8],
       [ 9,  6,  6,  7]])

In [55]:
np.concatenate((a1,a2))

array([[ 4,  3,  7,  9],
       [ 2,  3,  9,  6],
       [ 1,  4,  7,  6],
       [11,  4,  8,  7],
       [ 4,  2,  1, 11],
       [ 3,  3,  4,  4],
       [ 7,  9,  7,  8],
       [ 9,  6,  6,  7]])

In [56]:
np.concatenate((a1,a2),axis=0)

array([[ 4,  3,  7,  9],
       [ 2,  3,  9,  6],
       [ 1,  4,  7,  6],
       [11,  4,  8,  7],
       [ 4,  2,  1, 11],
       [ 3,  3,  4,  4],
       [ 7,  9,  7,  8],
       [ 9,  6,  6,  7]])

In [57]:
np.concatenate((a1,a2),axis=1)

array([[ 4,  3,  7,  9,  4,  2,  1, 11],
       [ 2,  3,  9,  6,  3,  3,  4,  4],
       [ 1,  4,  7,  6,  7,  9,  7,  8],
       [11,  4,  8,  7,  9,  6,  6,  7]])

In [58]:
a = np.random.randint(11,100,(8,8))
a

array([[54, 99, 93, 92, 12, 81, 75, 93],
       [75, 37, 46, 88, 27, 46, 24, 79],
       [28, 60, 44, 80, 84, 47, 54, 89],
       [16, 42, 70, 34, 62, 98, 68, 47],
       [49, 67, 57, 25, 67, 22, 73, 52],
       [48, 69, 87, 22, 74, 90, 14, 61],
       [46, 67, 49, 50, 56, 26, 22, 57],
       [70, 73, 16, 98, 75, 91, 97, 99]])

In [59]:
a>60

array([[False,  True,  True,  True, False,  True,  True,  True],
       [ True, False, False,  True, False, False, False,  True],
       [False, False, False,  True,  True, False, False,  True],
       [False, False,  True, False,  True,  True,  True, False],
       [False,  True, False, False,  True, False,  True, False],
       [False,  True,  True, False,  True,  True, False,  True],
       [False,  True, False, False, False, False, False, False],
       [ True,  True, False,  True,  True,  True,  True,  True]])

In [60]:
a[a>70]

array([99, 93, 92, 81, 75, 93, 75, 88, 79, 80, 84, 89, 98, 73, 87, 74, 90,
       73, 98, 75, 91, 97, 99])

In [62]:
b=a[a>50]
b[b>70]  # will satisfy both the conditions

array([99, 93, 92, 81, 75, 93, 75, 88, 79, 80, 84, 89, 98, 73, 87, 74, 90,
       73, 98, 75, 91, 97, 99])

In [63]:
a = np.random.randint(10,100,(10,10))
a

array([[48, 36, 72, 59, 44, 72, 14, 22, 17, 85],
       [51, 86, 80, 78, 82, 23, 20, 93, 51, 67],
       [75, 31, 55, 31, 35, 36, 18, 56, 72, 72],
       [88, 90, 91, 56, 33, 72, 50, 91, 59, 50],
       [13, 16, 46, 25, 86, 99, 93, 78, 81, 81],
       [45, 58, 22, 94, 61, 95, 97, 48, 14, 33],
       [85, 25, 22, 20, 99, 53, 86, 87, 69, 25],
       [92, 49, 13, 25, 95, 14, 80, 99, 56, 34],
       [66, 81, 67, 10, 67, 78, 95, 91, 47, 90],
       [61, 31, 39, 59, 50, 17, 34, 27, 14, 51]])

In [69]:
# access from 3rd row to 8th row,column from 2 to 8 ie, 31 to 72 -> 49 to 56

a[2:8,1:9]



array([[31, 55, 31, 35, 36, 18, 56, 72],
       [90, 91, 56, 33, 72, 50, 91, 59],
       [16, 46, 25, 86, 99, 93, 78, 81],
       [58, 22, 94, 61, 95, 97, 48, 14],
       [25, 22, 20, 99, 53, 86, 87, 69],
       [49, 13, 25, 95, 14, 80, 99, 56]])

In [70]:
a[2:8:2,1:9:2] 

array([[31, 31, 36, 56],
       [16, 25, 99, 78],
       [25, 20, 53, 87]])

In [71]:
# access from 3rd row to 8th row,column from 2 to 8 ie, 31 to 72 -> 49 to 56 reverse
a[7:1:-1,8:0:-1]

array([[56, 99, 80, 14, 95, 25, 13, 49],
       [69, 87, 86, 53, 99, 20, 22, 25],
       [14, 48, 97, 95, 61, 94, 22, 58],
       [81, 78, 93, 99, 86, 25, 46, 16],
       [59, 91, 50, 72, 33, 56, 91, 90],
       [72, 56, 18, 36, 35, 31, 55, 31]])