# NumPy
- Short for Numerical Python
- Foundational Package for Numerical computing in python
- Provides an ndarray object which is an efficient multidimensional array providing fast array oriented operations
- Provides a lot of functions

In [2]:
import numpy as np

# Creating ndarrays

##### Creating ndarray from an object

In [2]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
a1

array([1, 2, 3, 4, 5])

In [3]:
type(a1)

numpy.ndarray

In [4]:
t1 = (1,2,3,4,5)
a1 = np.array(t1)
a1

array([1, 2, 3, 4, 5])

In [5]:
a1 = np.array(range(1,11))
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a1.shape

(10,)

In [8]:
a1.dtype

dtype('int32')

In [7]:
a1.ndim

1

In [8]:
a1 = np.array([[1,2,3], [4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a1.shape

(2, 3)

In [10]:
a1.ndim

2

In [12]:
a1 = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
a1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
a1.shape

(2, 2, 2)

In [13]:
a1.ndim

3

In [14]:
a = np.array([1,2,3,4,5], dtype = float)
a

array([1., 2., 3., 4., 5.])

In [15]:
a.dtype

dtype('float64')

In [16]:
a = np.array([1.5,2.6,3.1,4.8,5.2], dtype = int)
a

array([1, 2, 3, 4, 5])

In [17]:
a.dtype

dtype('int32')

### Typecasting ndarrays

In [20]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [18]:
a = a.astype(float)
a

array([1., 2., 3., 4., 5.])

In [19]:
a = a.astype(int)
a

array([1, 2, 3, 4, 5])

### Creating ndarrays by specifying a range

In [20]:
a1 = np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a1 = np.arange(0,21,2)
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a1 = np.arange(10, dtype = float)
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Creating ndarrays of ones

In [27]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [25]:
np.ones((5,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Creating ndarray of zeros

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Creating ndarray of a specific value

In [30]:
np.full((4,5), fill_value = 6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

### Creating an identity matrix

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# --------------------------------------------------------------------------------------
# Operations on ndarrays

In [31]:
a1 = np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

In [32]:
# list
l = [1,2,3,4,5,6]
l + 2

TypeError: can only concatenate list (not "int") to list

In [33]:
a1 + 2

array([3, 4, 5, 6, 7, 8])

In [34]:
a2 = np.array([4,5,6,7,8,9])
a2

array([4, 5, 6, 7, 8, 9])

In [36]:
a1 + a2

array([ 5,  7,  9, 11, 13, 15])

In [35]:
a1 + [2,3,4,5,6,7]

array([ 3,  5,  7,  9, 11, 13])

In [38]:
a1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [36]:
print(a1)
print(a2)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [39]:
a1 * a2

array([ 4, 10, 18, 28, 40, 54])

In [37]:
a1 = np.array([2,4,6,8,10])
a1 / 2

array([1., 2., 3., 4., 5.])

In [38]:
a1 // 2

array([1, 2, 3, 4, 5], dtype=int32)

In [39]:
a1 % 3

array([2, 1, 0, 2, 1], dtype=int32)

In [40]:
a1 ** 2

array([  4,  16,  36,  64, 100], dtype=int32)

In [51]:
a2 = np.array([2,3,4,5,6])
a1 ** a2

array([      4,      64,    1296,   32768, 1000000], dtype=int32)

In [41]:
a1

array([ 2,  4,  6,  8, 10])

In [52]:
2 / a1

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [51]:
l1 = [1,2,3,4,5,6]
l1 < 4

TypeError: '<' not supported between instances of 'list' and 'int'

In [52]:
a1 = np.array([1,2,3,4,5,6])
a1 < 4

array([ True,  True,  True, False, False, False])

In [50]:
# list
l1 = [5,1,4,5,3,6]
l2 = [7,4,2,1,6,7]
l1 < l2

True

In [43]:
a1 = np.array([2,1,4,5,3,6])
a2 = np.array([3,4,2,1,6,7])

In [44]:
a1 < a2

array([ True,  True, False, False,  True,  True])

In [45]:
a1 > a2

array([False, False,  True,  True, False, False])

In [46]:
a1 <= a2

array([ True,  True, False, False,  True,  True])

In [47]:
a1 == a2

array([False, False, False, False, False, False])

In [48]:
# Operation between two ndarrays not possible if shapes are not same
a1 = np.array([1,2,3,4,5])
a2 = np.array([2,3,4,5,6,7])

a1 + a2

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

## Indexing and Slicing ndarrays

In [53]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a[0]

0

In [55]:
a[1]

1

In [56]:
a[6]

6

In [57]:
a[-1]

9

In [58]:
a[-2]

8

In [59]:
a[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [60]:
a[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a[-8:-3]

array([2, 3, 4, 5, 6])

In [62]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Reshape and Transpose

In [63]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [64]:
a.shape

(16,)

In [65]:
a.ndim

1

In [66]:
a = a.reshape((16,1))
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [67]:
a.shape

(16, 1)

In [68]:
a.ndim

2

In [69]:
a = a.reshape((1,16))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [70]:
a.shape

(1, 16)

In [71]:
a.ndim

2

In [72]:
a.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
a.reshape((2,2,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [73]:
a = np.arange(36)
a.reshape((1,36))
a.reshape((2,18))
a.reshape((3,12))
a.reshape((4,9))
a.reshape((6,6))
a.reshape((9,4))
a.reshape((12,3))
a.reshape((18,2))
a.reshape((36,1))
print('Total possible 2d shapes : ', 9)

Total possible 2d shapes :  9


In [74]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

# ----------------------------------------------------------------------------------

# Functions

In [75]:
a = np.array([2,4,3,6,5,8,7,9,1,0])
a

array([2, 4, 3, 6, 5, 8, 7, 9, 1, 0])

In [76]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
s = np.square(a)
s

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [78]:
np.sqrt(s)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [79]:
a = np.array([8,27,64])
np.cbrt(a)

array([2., 3., 4.])

In [80]:
np.abs([-1,2,3,-5,-6,-2,6])

array([1, 2, 3, 5, 6, 2, 6])

In [81]:
np.add([1,2,3],[4,5,6])

array([5, 7, 9])

In [82]:
np.subtract([4,5,6],[1,2,3])

array([3, 3, 3])

In [83]:
np.multiply([1,2,3],[2,3,4])

array([ 2,  6, 12])

In [84]:
a1 = np.array([2,1,4,5,3,6])
a2 = np.array([3,4,2,1,6,5])

In [84]:
np.maximum(a1,a2)

array([3, 4, 4, 5, 6, 6])

In [85]:
np.minimum(a1,a2)

array([2, 1, 2, 1, 3, 5])

In [86]:
np.greater(a1,a2)

array([False, False,  True,  True, False,  True])

In [87]:
np.less(a1,a2)

array([ True,  True, False, False,  True, False])

In [88]:
a1 = np.arange(21)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [90]:
np.mean([1,2,3,4,5,6,7,8,9])

5.0

In [93]:
np.var([1,2,3,4,5,6,7,8,9])

6.666666666666667

In [94]:
np.std([1,2,3,4,5,6,7,8,9])

2.581988897471611

In [95]:
np.median(a1)

10.0

In [89]:
a1.mean()

10.0

In [91]:
a1.var()

36.666666666666664

In [92]:
a1.std()

6.0553007081949835

In [97]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [22]:
a.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

In [99]:
a.min()

1

In [100]:
a.max()

10

In [101]:
a.sum()

55

In [102]:
a = np.arange(64).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [103]:
a.shape

(8, 8)

In [104]:
a.mean()

31.5

In [105]:
a.mean(axis = 0)

array([28., 29., 30., 31., 32., 33., 34., 35.])

In [106]:
a.mean(axis = 1)

array([ 3.5, 11.5, 19.5, 27.5, 35.5, 43.5, 51.5, 59.5])

In [107]:
a.std()

18.472953201911167

In [108]:
a.std(axis = 0)

array([18.33030278, 18.33030278, 18.33030278, 18.33030278, 18.33030278,
       18.33030278, 18.33030278, 18.33030278])

In [109]:
a.std(axis = 1)

array([2.29128785, 2.29128785, 2.29128785, 2.29128785, 2.29128785,
       2.29128785, 2.29128785, 2.29128785])

In [110]:
a.max()

63

In [111]:
a.max(axis = 0)

array([56, 57, 58, 59, 60, 61, 62, 63])

In [112]:
a.max(axis = 1)

array([ 7, 15, 23, 31, 39, 47, 55, 63])

In [113]:
x = np.array([10,30,80,20,40])
x

array([10, 30, 80, 20, 40])

In [114]:
np.argmax(x)

2

In [115]:
np.argmin(x)

0

In [116]:
a1 = np.array([2,1,5,4,3,5,6,7,3,10,2,3]).reshape(3,4)
a1

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [117]:
np.argmax(a1)

9

In [118]:
np.argmax(a1, axis = 0)

array([1, 2, 1, 1], dtype=int64)

In [120]:
np.argmax(a1, axis = 1)

array([2, 3, 1], dtype=int64)

In [119]:
np.argmin(a1, axis = 0)

array([0, 0, 2, 2], dtype=int64)

In [115]:
np.argmin(a1, axis = 1)

array([1, 0, 2], dtype=int64)

In [121]:
a1

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [122]:
a1.ravel()

array([ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3])

In [123]:
a2 = a1.reshape(1,3,4)
a2

array([[[ 2,  1,  5,  4],
        [ 3,  5,  6,  7],
        [ 3, 10,  2,  3]]])

In [124]:
a2.shape

(1, 3, 4)

In [125]:
a2 = a2.squeeze()
a2

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [126]:
a2.shape

(3, 4)

In [127]:
a2 = a2.reshape(3,4,1)
a2

array([[[ 2],
        [ 1],
        [ 5],
        [ 4]],

       [[ 3],
        [ 5],
        [ 6],
        [ 7]],

       [[ 3],
        [10],
        [ 2],
        [ 3]]])

In [128]:
a2 = a2.squeeze()
a2

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [129]:
a2.shape

(3, 4)

### Determinant and Inverse

In [130]:
from numpy.linalg import det, inv, eig
a = np.array([4,3,7,9,2,3,9,6,1,4,7,6,11,4,8,7]).reshape((4,4))
a

array([[ 4,  3,  7,  9],
       [ 2,  3,  9,  6],
       [ 1,  4,  7,  6],
       [11,  4,  8,  7]])

In [131]:
det(a)

527.0000000000001

In [132]:
inv(a)

array([[-0.0170778 , -0.02087287, -0.07969639,  0.10815939],
       [-0.22580645, -0.38709677,  0.61290323,  0.09677419],
       [-0.10436433,  0.31688805, -0.15370019, -0.0056926 ],
       [ 0.27514231, -0.10815939, -0.04933586, -0.07590133]])

In [133]:
eig(a)

(array([22.97864964,  3.76499269, -4.34011564, -1.40352668]),
 array([[-0.51289911, -0.39468612,  0.5270535 ,  0.05108621],
        [-0.41676444,  0.52758299,  0.07812217, -0.85784205],
        [-0.37954612,  0.5045306 ,  0.33673147,  0.494701  ],
        [-0.64744625, -0.55796767, -0.77635266, -0.12949184]]))

### Concatenation

In [134]:
a1 = np.arange(5)
a2 = np.arange(5,10)

In [135]:
np.concatenate((a1,a2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
a1 = a1.reshape(1,5)
a2 = a2.reshape(1,5)
print(a1)
print(a2)

[[0 1 2 3 4]]
[[5 6 7 8 9]]


In [137]:
np.concatenate((a1,a2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [138]:
np.concatenate((a1,a2), axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [139]:
np.concatenate((a1,a2), axis = 1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [140]:
a1 = a
a2 = a.T
print(a1)
print()
print(a2)

[[ 4  3  7  9]
 [ 2  3  9  6]
 [ 1  4  7  6]
 [11  4  8  7]]

[[ 4  2  1 11]
 [ 3  3  4  4]
 [ 7  9  7  8]
 [ 9  6  6  7]]


In [141]:
np.concatenate((a1,a2), axis = 0)

array([[ 4,  3,  7,  9],
       [ 2,  3,  9,  6],
       [ 1,  4,  7,  6],
       [11,  4,  8,  7],
       [ 4,  2,  1, 11],
       [ 3,  3,  4,  4],
       [ 7,  9,  7,  8],
       [ 9,  6,  6,  7]])

In [142]:
np.concatenate((a1,a2), axis = 1)

array([[ 4,  3,  7,  9,  4,  2,  1, 11],
       [ 2,  3,  9,  6,  3,  3,  4,  4],
       [ 1,  4,  7,  6,  7,  9,  7,  8],
       [11,  4,  8,  7,  9,  6,  6,  7]])

# Random numbers

In [148]:
np.random.randint(1,10)

3

In [151]:
np.random.randint(50)

11

In [153]:
np.random.randint(1,100,10)

array([93, 20, 32, 57, 57, 21, 28, 51, 22, 82])

In [155]:
np.random.randint(11,100,(10,10))

array([[96, 99, 48, 36, 43, 28, 77, 64, 92, 93],
       [82, 24, 88, 80, 38, 36, 16, 72, 68, 63],
       [89, 74, 22, 61, 31, 63, 45, 32, 78, 56],
       [14, 86, 74, 16, 47, 13, 25, 39, 84, 16],
       [49, 81, 38, 89, 82, 15, 16, 75, 17, 60],
       [24, 38, 40, 15, 51, 84, 99, 17, 99, 54],
       [70, 23, 62, 54, 39, 22, 17, 11, 52, 57],
       [87, 58, 95, 66, 47, 32, 28, 39, 88, 44],
       [84, 89, 48, 58, 92, 73, 88, 75, 32, 26],
       [81, 12, 57, 52, 34, 46, 94, 71, 11, 37]])

In [156]:
np.random.rand(10)

array([1.76814114e-01, 7.39295657e-01, 2.19638173e-01, 6.10844819e-01,
       1.12657851e-01, 5.96218820e-01, 3.00841592e-04, 1.61929926e-01,
       1.85025322e-01, 9.49693806e-01])

In [157]:
np.random.randn(10)

array([ 0.53311173,  1.51772831,  0.15965479, -0.64174755,  0.68166702,
        1.60969144, -0.26903086, -0.36577269,  0.30886807,  0.10466335])

In [158]:
np.random.randn(3,4)

array([[ 0.26637228, -1.38833156,  0.23230733, -2.1458538 ],
       [-0.97378295,  2.1201828 ,  0.05121573,  0.80329421],
       [ 1.02198845,  1.21912687, -0.34324688, -0.16104361]])

# Conditional Indexing

In [159]:
a = np.random.randint(11,100,(8,8))
a

array([[69, 55, 47, 72, 97, 82, 27, 82],
       [53, 39, 44, 87, 27, 12, 57, 28],
       [98, 52, 24, 64, 55, 24, 51, 17],
       [44, 95, 58, 53, 29, 49, 46, 21],
       [59, 12, 86, 83, 57, 86, 16, 18],
       [79, 88, 13, 93, 54, 31, 93, 58],
       [25, 77, 44, 52, 41, 65, 95, 25],
       [42, 25, 28, 52, 42, 46, 84, 86]])

In [160]:
a > 50

array([[ True,  True, False,  True,  True,  True, False,  True],
       [ True, False, False,  True, False, False,  True, False],
       [ True,  True, False,  True,  True, False,  True, False],
       [False,  True,  True,  True, False, False, False, False],
       [ True, False,  True,  True,  True,  True, False, False],
       [ True,  True, False,  True,  True, False,  True,  True],
       [False,  True, False,  True, False,  True,  True, False],
       [False, False, False,  True, False, False,  True,  True]])

In [161]:
a[a > 50]

array([69, 55, 72, 97, 82, 82, 53, 87, 57, 98, 52, 64, 55, 51, 95, 58, 53,
       59, 86, 83, 57, 86, 79, 88, 93, 54, 93, 58, 77, 52, 65, 95, 52, 84,
       86])

In [162]:
a[a < 50]

array([47, 27, 39, 44, 27, 12, 28, 24, 24, 17, 44, 29, 49, 46, 21, 12, 16,
       18, 13, 31, 25, 44, 41, 25, 42, 25, 28, 42, 46])

In [163]:
a[a <= 40]

array([27, 39, 27, 12, 28, 24, 24, 17, 29, 21, 12, 16, 18, 13, 31, 25, 25,
       25, 28])

In [164]:
a[a == 16]

array([16])

In [165]:
b = a[a < 40]
b[b > 20]

array([27, 39, 27, 28, 24, 24, 29, 21, 31, 25, 25, 25, 28])

# Slicing in Multidimensional Arrays

In [3]:
a = np.random.randint(10,100,(10,10))
a

array([[37, 54, 38, 26, 70, 44, 66, 70, 55, 49],
       [46, 80, 49, 44, 18, 71, 55, 42, 32, 48],
       [62, 35, 80, 10, 62, 19, 82, 27, 17, 44],
       [66, 73, 65, 20, 19, 28, 77, 53, 39, 64],
       [32, 76, 10, 15, 76, 10, 48, 51, 82, 74],
       [82, 34, 31, 62, 89, 40, 64, 78, 30, 67],
       [98, 31, 92, 69, 24, 31, 82, 46, 77, 16],
       [78, 50, 97, 30, 76, 12, 55, 85, 98, 24],
       [87, 13, 28, 29, 99, 53, 96, 12, 22, 82],
       [56, 29, 12, 86, 39, 95, 40, 22, 73, 77]])

In [5]:
a[8::-1,2:9]

array([[28, 29, 99, 53, 96, 12, 22],
       [97, 30, 76, 12, 55, 85, 98],
       [92, 69, 24, 31, 82, 46, 77],
       [31, 62, 89, 40, 64, 78, 30],
       [10, 15, 76, 10, 48, 51, 82],
       [65, 20, 19, 28, 77, 53, 39],
       [80, 10, 62, 19, 82, 27, 17],
       [49, 44, 18, 71, 55, 42, 32],
       [38, 26, 70, 44, 66, 70, 55]])

In [182]:
print(a[8::-1, 2:9])
print()
print(a[8::-1, 8:1:-1])

[[44 63 16 51 34 42 74]
 [29 61 77 64 31 87 84]
 [88 57 12 13 10 32 46]
 [35 95 61 59 97 48 33]
 [28 98 75 99 48 42 15]
 [46 44 62 73 90 15 65]
 [17 74 69 40 58 34 56]
 [49 21 65 56 32 50 11]
 [57 25 71 87 67 98 43]]

[[74 42 34 51 16 63 44]
 [84 87 31 64 77 61 29]
 [46 32 10 13 12 57 88]
 [33 48 97 59 61 95 35]
 [15 42 48 99 75 98 28]
 [65 15 90 73 62 44 46]
 [56 34 58 40 69 74 17]
 [11 50 32 56 65 21 49]
 [43 98 67 87 71 25 57]]


In [167]:
a.ndim

2

In [168]:
a.shape

(10, 10)

In [169]:
a[0]

array([30, 38, 57, 25, 71, 87, 67, 98, 43, 82])

In [170]:
a[1]

array([71, 18, 49, 21, 65, 56, 32, 50, 11, 64])

In [171]:
a[:3]

array([[30, 38, 57, 25, 71, 87, 67, 98, 43, 82],
       [71, 18, 49, 21, 65, 56, 32, 50, 11, 64],
       [36, 44, 17, 74, 69, 40, 58, 34, 56, 67]])

In [172]:
a[0][3]

25

In [175]:
a[:5, :4]

array([[30, 38, 57, 25],
       [71, 18, 49, 21],
       [36, 44, 17, 74],
       [35, 83, 46, 44],
       [18, 12, 28, 98]])

In [176]:
a[:8, :7]

array([[30, 38, 57, 25, 71, 87, 67],
       [71, 18, 49, 21, 65, 56, 32],
       [36, 44, 17, 74, 69, 40, 58],
       [35, 83, 46, 44, 62, 73, 90],
       [18, 12, 28, 98, 75, 99, 48],
       [98, 14, 35, 95, 61, 59, 97],
       [68, 57, 88, 57, 12, 13, 10],
       [44, 66, 29, 61, 77, 64, 31]])

In [177]:
a[1:8,2:6]

array([[49, 21, 65, 56],
       [17, 74, 69, 40],
       [46, 44, 62, 73],
       [28, 98, 75, 99],
       [35, 95, 61, 59],
       [88, 57, 12, 13],
       [29, 61, 77, 64]])

In [178]:
a[1:9, 4:9:2]

array([[65, 32, 11],
       [69, 58, 56],
       [62, 90, 65],
       [75, 48, 15],
       [61, 97, 33],
       [12, 10, 46],
       [77, 31, 84],
       [16, 34, 74]])

In [179]:
a[1:9:2, 1:8:3]

array([[18, 65, 50],
       [83, 62, 15],
       [14, 61, 48],
       [66, 77, 87]])

In [181]:
a[0:8,5::-1]

array([[87, 71, 25, 57, 38, 30],
       [56, 65, 21, 49, 18, 71],
       [40, 69, 74, 17, 44, 36],
       [73, 62, 44, 46, 83, 35],
       [99, 75, 98, 28, 12, 18],
       [59, 61, 95, 35, 14, 98],
       [13, 12, 57, 88, 57, 68],
       [64, 77, 61, 29, 66, 44]])